---
- name: Dynamically add new Bastion VM to the inventory
  add_host:
    ansible_ssh_user: root
    ansible_ssh_host: "{{ hostvars['hypervisor']['public_ip_address'] }}"
    ansible_ssh_port: 8000
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -i "{{ ocp4_aio_ssh_key_path }}"'
    hostname: bastion-vm
    groups: bastion-vm
